CREATE TABLE clickhouse_local.kafka_engine (
    `id`                                  String,
    `merchant_id`                         String,
    `store_id`                            String,
    `transaction_timestamp`               String,
    `status_changed_timestamp`            String,
    `transaction_date`                    String,
    `transaction_type`                    String,
    `transaction_status`                  String,
    `previous_transaction_status`         String,
    `transaction_expired_time`            String,
    `transaction_valid_time`              String,
    `transaction_paid_at`                 String,
    `channel`                             String,
    `channel_group`                       String,
    `amount`                              String,
    `fee`                                 String,
    `provider_fee`                        String,
    `fee_type`                            String,
    `fee_id`                              String,
    `merchant_fixed_fee`                  String,
    `merchant_percentage_fee`             String,
    `merchant_amount`                     String,
    `provider_id`                         String,
    `provider_channel_id`                 String,
    `provider_fee_id`                     String,
    `provider_snap`                       String,
    `provider_response_code`              String,
    `provider_response_message`           String,
    `provider_reference`                  String,
    `provider_status_changed_timestamp`   String,
    `provider_previous_response_code`     String,
    `provider_previous_response_message`  String,
    `reference`                           String,
    `merchant_reference`                  String,
    `merchant_callback_url`               String,
    `merchant_callback_response_code`     String,
    `merchant_callback_response_message`  String,
    `merchant_callback_sent_timestamp`    String,
    `revenue`                             String,
    `bank_code`                           String,
    `bank_account_id`                     String,
    `additional_info`                     String,
    `acquirer`                            String,
    `settlement_status`                   String,
    `settled_at`                          String,
    `is_settled`                          String,
    `settlement_batch_id`                 String,
    `response_code`                       String,
    `response_message`                    String,
    `previous_response_code`              String,
    `previous_response_message`           String,
    `currency`                            String,
    `retrieval_reference_number`          String,
    `mpan`                                String,
    `payer_name`                          String,
    `payer_phone_number`                  String,
    `created_at`                          String,
    `updated_at`                          String,
    `deleted_at`                          String
) ENGINE = Kafka SETTINGS kafka_broker_list = 'broker-1:9092,broker-2:9092,broker-3:9092',
kafka_topic_list = 'transaction-log',
kafka_format = 'JSONEachRow',
kafka_group_name = 'transaction-log-ch',
kafka_num_consumers = 1,
kafka_thread_per_consumer = 1,
kafka_client_id = 'transaction-log-consumer'
