CREATE TABLE clickhouse_local.kafka_merchant_api_logs (
    `transaction_reference` String,
    `endpoint_url` String,
    `signature` String,
    `request_payload` String,
    `response_payload` String,
    `req_header` String,
    `resp_header` String,
    `http_status_code` String,
    `request_date` String,
    `request_timestamp` String,
    `response_timestamp` String,
    `merchant_id` String,
    `merchant_name` String,
    `merchant_channel_id` String,
    `channel` String,
    `error_message` String
) ENGINE = Kafka SETTINGS kafka_broker_list = 'broker-1:9092,broker-2:9092,broker-3:9092',
kafka_topic_list = 'merchant-api-log',
kafka_format = 'JSONEachRow',
kafka_group_name = 'merchant-api-log-ch',
kafka_num_consumers = 1,
kafka_thread_per_consumer = 1,
kafka_client_id = 'merchant-api-log-consumer'